return {
  {
    "williamboman/mason.nvim",
    build = ":MasonUpdate",
    cmd = { "Mason", "MasonInstall", "MasonUninstall", "MasonLog", "MasonUpdate" },
    opts = {
      ui = {
        border = "rounded",
        icons = {
          package_installed = "✓",
          package_pending = "➜",
          package_uninstalled = "✗",
        },
      },
    },
  },
  {
    "williamboman/mason-lspconfig.nvim",
    dependencies = { "williamboman/mason.nvim" },
  },
  {
    "WhoIsSethDaniel/mason-tool-installer.nvim",
    event = "VeryLazy",
    opts = {
      ensure_installed = {
        "bash-language-server",
        "clangd",
        "clang-format",
        "css-lsp",
        "dockerfile-language-server",
        "eslint-lsp",
        "gopls",
        "goimports",
        "gofumpt",
        "html-lsp",
        "intelephense",
        "jdtls",
        "json-lsp",
        "kotlin-language-server",
        "lua-language-server",
        "marksman",
        "pyright",
        "ruff-lsp",
        "ruff",
        "rust-analyzer",
        "tailwindcss-language-server",
        "taplo",
        "terraform-ls",
        "typescript-language-server",
        "yaml-language-server",
        "yamllint",
        "yamlfmt",
        "stylua",
        "black",
        "isort",
        "prettierd",
        "biome",
        "shfmt",
        "shellcheck",
        "markdownlint",
        "debugpy",
        "js-debug-adapter",
        "delve",
        "codelldb",
      },
    },
  },
  {
    "neovim/nvim-lspconfig",
    event = { "BufReadPost", "BufNewFile" },
    dependencies = {
      "williamboman/mason.nvim",
      "williamboman/mason-lspconfig.nvim",
      "folke/neodev.nvim",
      "b0o/schemastore.nvim",
    },
    config = function()
      require("lsp").setup()
    end,
  },
  {
    "folke/neodev.nvim",
    ft = { "lua" },
    opts = {},
  },
}
